### ISSUE TITLE
Article Enhancer for GitHub Newsfeed

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#922]
Please add an article enhancer for GitHub RSS Newsfeed. It looks currently strange.
![screenshot](https://cloud.githubusercontent.com/assets/4741199/12884905/ab681b82-ce61-11e5-82b9-332ef63276c0.png)

I think this would do it for the avatar:
```css
img {
    max-width: 50px;
    float: left;
    padding: 0px 10px 10px 0px;
}
```
